name: appinncatalogo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  app_links: ^6.4.1
  cloud_functions: ^6.0.3
  url_launcher: ^6.3.2
  firebase_app_check: ^0.4.1+1
  path_provider: ^2.1.5
  http: ^1.5.0
  intl: ^0.20.2
  share_plus: ^12.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
